version: '3.7'
services:
  photobook_pg:
    image: postgres:latest
    container_name: photobook_pg
    restart: unless-stopped
    environment:
      POSTGRES_DB: photobook
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - 5436:5432
    logging:
      options:
        max-size: "10m"
        max-file: "10"
