version: '3.7'
services:
  hr_pg:
    image: postgres:latest
    container_name: photobook_pg
    restart: unless-stopped
    environment:
      POSTGRES_DB: photobook
      POSTGRES_USER: photobook
      POSTGRES_PASSWORD: photobook123
    ports:
      - 5436:5432
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    volumes:
      - /var/lib/docker/volumes/hr_vol/_data

