version: '3.7'
services:
  photobook_pg:
    image: postgres:latest
    container_name: photobook_pg
    restart: unless-stopped
    environment:
      POSTGRES_DB: photobook
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - 5436:5432
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  minio:
    image: minio/minio
    restart: unless-stopped
    ports:
      - "443:443"
      - "4443:4443"
    volumes:
      - ./data:/data
    environment:
      - "MINIO_ACCESS_KEY=minio"
      - "MINIO_SECRET_KEY=minio123"
    command: server --address ":443" --console-address ":4443" /data

