spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/photobook?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: photobook
    password: photobook123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true
        temp.use_jdbc_metadata_defaults: false
        synonyms: true
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        default-schema: OSADMIN
        enable_lazy_load_no_trans: true
    show-sql: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 582427921464-29a66bkpo68kkl1d835qn00gc0oskqrn.apps.googleusercontent.com
            client-secret: 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
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
app:
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 86400000
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8080
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect